/**
 * Detects orphan FILES inside surviving plugin skill directories.
 *
 * `clean-orphaned-skills.ts` removes whole skill *directories* that have no
 * upstream owner. This script complements it by finding individual files
 * left behind inside skill directories that still exist — for example, when
 * upstream renames a sub-file (`workflow-x.md` → `workflow-y.md`) while
 * keeping the skill directory, the old file is never cleaned up because
 * sync only copies/overwrites.
 *
 * Multiple upstream sources can contribute files into the same plugin skill
 * directory (e.g., `skills/research/` receives content from both core and
 * GDS). The "expected" set is therefore the UNION across all enabled
 * sources, plus known generated files (SKILL.md) and intentional
 * plugin-only data.
 *
 * Run:
 *   bun scripts/find-orphan-files.ts                     # report all
 *   bun scripts/find-orphan-files.ts --source core       # filter report
 *   bun scripts/find-orphan-files.ts --delete            # delete orphans
 */

import { exists, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { PLUGIN, ROOT } from './lib/config.ts';
import { listFilesRecursive } from './lib/fs-utils.ts';
import {
  getEnabledSources,
  getSource,
  shouldSkipContentFile,
  type UpstreamSource,
} from './lib/upstream-sources.ts';
import { getWorkflowEntries } from './lib/workflow-iterator.ts';

const DELETE = process.argv.includes('--delete');
const SOURCE_FILTER = (() => {
  const idx = process.argv.indexOf('--source');
  return idx >= 0 ? process.argv[idx + 1] : undefined;
})();

/**
 * Files/relative-paths always expected in plugin skill dirs even though
 * they aren't part of the raw upstream copy:
 *   - SKILL.md is generated by `generate:skills` from upstream workflow.yaml
 *     (at the skill root, not nested).
 */
const ALWAYS_EXPECTED_AT_ROOT = new Set<string>(['SKILL.md']);

interface ExpectedEntry {
  /** Source ids that contribute this file — for reporting context */
  contributors: Set<string>;
}

/** Per skill: map<relativePath, ExpectedEntry> */
type ExpectedBySkill = Map<string, Map<string, ExpectedEntry>>;

interface Orphan {
  skill: string;
  relativePath: string;
  absolutePath: string;
}

async function buildExpected(
  sources: UpstreamSource[],
): Promise<ExpectedBySkill> {
  const expected: ExpectedBySkill = new Map();

  for (const source of sources) {
    const upstreamRoot = join(ROOT, '.upstream', source.localPath);
    if (!(await exists(join(upstreamRoot, '.git')))) {
      console.log(
        `⚠ Skipping ${source.id}: repo not cloned at ${upstreamRoot}`,
      );
      continue;
    }

    const entries = await getWorkflowEntries(source, upstreamRoot);
    for (const entry of entries) {
      let perSkill = expected.get(entry.skillName);
      if (!perSkill) {
        perSkill = new Map();
        expected.set(entry.skillName, perSkill);
      }

      // Upstream files (filtered via the same rules sync applies)
      const upstreamFiles = await listFilesRecursive(entry.upstreamDir);
      for (const rel of upstreamFiles) {
        const fileName = rel.split('/').at(-1) ?? rel;
        if (shouldSkipContentFile(source, fileName)) continue;
        const existing = perSkill.get(rel) ?? { contributors: new Set() };
        existing.contributors.add(source.id);
        perSkill.set(rel, existing);
      }

      // SKILL.md at skill root is generated, always expected
      const rootSkill = perSkill.get('SKILL.md') ?? {
        contributors: new Set(),
      };
      rootSkill.contributors.add('generated');
      perSkill.set('SKILL.md', rootSkill);

      // Plugin-only data scoped to this skill (intentionally preserved)
      for (const preserved of source.pluginOnlyData ?? []) {
        if (!preserved.startsWith(`${entry.skillName}/`)) continue;
        const rel = preserved.slice(entry.skillName.length + 1);
        const entry2 = perSkill.get(rel) ?? { contributors: new Set() };
        entry2.contributors.add(`${source.id}(plugin-only)`);
        perSkill.set(rel, entry2);
      }
    }
  }

  return expected;
}

/**
 * Determine which skills are "owned" (received any contribution) by a
 * given source — used for filtering the report.
 */
async function skillsOwnedBy(source: UpstreamSource): Promise<Set<string>> {
  const owned = new Set<string>();
  const upstreamRoot = join(ROOT, '.upstream', source.localPath);
  if (!(await exists(join(upstreamRoot, '.git')))) return owned;
  const entries = await getWorkflowEntries(source, upstreamRoot);
  for (const entry of entries) owned.add(entry.skillName);
  return owned;
}

// === Main ===

console.log(
  DELETE
    ? 'DELETE mode — orphan files will be removed\n'
    : 'Report mode — no files will be changed (use --delete to remove)\n',
);

// Build expected across ALL enabled sources so union is correct
const allSources = getEnabledSources();
const expectedBySkill = await buildExpected(allSources);

// If --source filter, restrict reporting to skills contributed to by that source
let skillFilter: Set<string> | null = null;
if (SOURCE_FILTER) {
  const one = getSource(SOURCE_FILTER);
  if (!one) {
    console.error(`Unknown --source: ${SOURCE_FILTER}`);
    process.exit(1);
  }
  skillFilter = await skillsOwnedBy(one);
}

const SKILLS_DIR = join(PLUGIN, 'skills');
const orphans: Orphan[] = [];

for (const [skill, expected] of [...expectedBySkill].sort(([a], [b]) =>
  a.localeCompare(b),
)) {
  if (skillFilter && !skillFilter.has(skill)) continue;

  const skillDir = join(SKILLS_DIR, skill);
  if (!(await exists(skillDir))) continue;

  const pluginFiles = await listFilesRecursive(skillDir);
  for (const rel of pluginFiles) {
    if (expected.has(rel)) continue;
    if (ALWAYS_EXPECTED_AT_ROOT.has(rel)) continue;
    orphans.push({
      skill,
      relativePath: rel,
      absolutePath: join(skillDir, rel),
    });
  }
}

if (orphans.length === 0) {
  console.log('No orphan files found.');
  process.exit(0);
}

// Group for report
const bySkill = new Map<string, Orphan[]>();
for (const o of orphans) {
  const list = bySkill.get(o.skill) ?? [];
  list.push(o);
  bySkill.set(o.skill, list);
}
for (const [skill, list] of [...bySkill].sort(([a], [b]) =>
  a.localeCompare(b),
)) {
  console.log(
    `  ${skill} (${list.length} orphan${list.length === 1 ? '' : 's'})`,
  );
  for (const o of list) {
    console.log(`    - ${o.relativePath}`);
  }
}

console.log(`\nTotal: ${orphans.length} orphan file(s)`);

if (!DELETE) {
  console.log('Run with --delete to remove them.');
  process.exit(0);
}

for (const o of orphans) {
  await rm(o.absolutePath);
  console.log(`  ✓ Removed: ${o.skill}/${o.relativePath}`);
}

console.log(`\n${orphans.length} orphan file(s) removed.`);
